name: ServerEssentials
author: Vašek Carlo Šrubař
version: '${project.version}'
api-version: '1.20'
main: me.vasek.serveressentials.ServerEssentials
commands:
  ban:
    description: Bans a player.
    usage: /ban <player> [reason]
    permission: serveressentials.ban
  unban:
    description: Unbans a player.
    usage: /unban <player>
    permission: serveressentials.unban
  kick:
    description: Kicks a player.
    usage: /kick <player> [reason]
    permission: serveressentials.kick
  playerinfo:
    description: Shows info about a player.
    usage: /playerinfo <player>
    permission: serveressentials.playerinfo
  op:
    description: Makes from regular person an OP
    usage: /op <player>
    permission: serveressentials.op
  mute:
    description: Mutes other player
    usage: /mute <player>
    permission: serveressentials.op
  unmute:
    description: Unmutes other player
    usage: /unmute <player>
    permission: serveressentials.op
  heal:
    description: Heals other player
    usage: /heal <player>
    permission: serveressentials.op
  tp:
    description: Teleports to other player
    usage: /tp <player>
    permission: serveressentials.op
  tpaccept:
    description: Accepts the teleportation of other player
    usage: /tpaccept
    permission: serveressentials.op
  tpdeny:
    description: Refuses the teleportation of other player
    usage: /tpdeny
    permission: serveressentials.op
  feed:
    description: Feeds other player
    usage: /feed <player>
    permission: serveressentials.op
  allcommands:
    description: Shows all commands
    usage: /allcommands
permissions:
  serveressentials.ban:
    description: Allows the player to ban others.
    default: op
  serveressentials.unban:
    description: Allows the player to unban others.
    default: op
  serveressentials.kick:
    description: Allows the player to kick others.
    default: op
  serveressentials.playerinfo:
    description: Allows the player to get info about others.
    default: op
  serveressentials.op:
    description: Allows player to op other players
    default: op
  serveressentials.mute:
    description: Allows player to mute other players
    default: op
  serveressentials.unmute:
    description: Allows player to unmute other players
    default: op
  serveressentials.heal:
    description: Allows player to heal other players
    default: op
  serveressentials.tp:
    description: Allows player to teleport to other player
    default: op
  serveressentials.tpaccept:
    description: Allows player to teleport to someone
    default: op
  serveressentials.tpdeny:
    description: Refuses player to teleport to someone
    default: op
  serveressentials.feed:
    description: Allows player to feed other player
    default: op

