name: ServerEssentials
author: Vašek Carlo Šrubař
version: '1.0-SNAPSHOT'
api-version: '1.20'
main: me.vasek.serveressentials.ServerEssentials
commands:
  ban:
    description: Bans a player.
    usage: /ban <player> [reason]
    permission: serveressentials.ban
  unban:
    description: Unbans a player.
    usage: /unban <player>
    permission: serveressentials.unban
  kick:
    description: Kicks a player.
    usage: /kick <player> [reason]
    permission: serveressentials.kick
  playerinfo:
    description: Shows info about a player.
    usage: /playerinfo <player>
    permission: serveressentials.playerinfo
  op:
    description: Makes from regular person an OP
    usage: /op <player>
    permission: serveressentials.op
  deop:
    description: Makes from OP person a regular player
    usage: /deop <player>
    permission: serveressentials.deop
  mute:
    description: Mutes other player
    usage: /mute <player>
    permission: serveressentials.op
  unmute:
    description: Unmutes other player
    usage: /unmute <player>
    permission: serveressentials.op
  allcommands:
    description: Shows all commands
    usage: /allcommands
permissions:
  serveressentials.ban:
    description: Allows the player to ban others.
    default: op
  serveressentials.unban:
    description: Allows the player to unban others.
    default: op
  serveressentials.kick:
    description: Allows the player to kick others.
    default: op
  serveressentials.playerinfo:
    description: Allows the player to get info about others.
    default: op
  serveressentials.op:
    description: Allows player to op other players
    default: op
  serveressentials.deop:
    description: Allows player to deop other players
    default: op
  serveressentials.mute:
    description: Allows player to mute other players
    default: op
  serveressentials.unmute:
    description: Allows player to unmute other players
    default: op

